<?php
/**
 * Configuration file for Form Builder
 * Generated by installer
 */

return [
    'db_host' => 'localhost',
    'db_name' => 'form_builder',
    'db_user' => 'root',
    'db_password' => 'September2018!',
    'site_name' => 'Dynamic Form Builder',
    'admin_email' => 'chris@sondelaconsuilting.com',
    'upload_dir' => 'uploads/',
    'max_file_size' => 5242880,
    'allowed_file_types' => 'jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,zip',
    'enable_captcha' => ,
    'session_timeout' => 1800,
];
